# Generated by Django 4.2.29 on 2026-03-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_currency_freelancetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='currency',
            name='rate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
