# Generated by Django 4.2.29 on 2026-03-22 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myapp', '0003_currency_rate_currency_rate_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('expiration', models.DateTimeField()),
                ('city', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('work_format', models.CharField(max_length=50)),
                ('salary_from', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency_rate_date', models.DateField(blank=True, null=True)),
                ('currency_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='myapp.currency')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('hired_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hired_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('apply', 'Apply')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
