# Generated by Django 4.2.29 on 2026-03-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_chatroom_message_vacancy_notification_interaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='schedule',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
